### PR TITLE
Replace tabs with spaces

### PR DESCRIPTION
**Pull request by leoheck**
So the table will be always formatted no matter the text editor.

### CODE REVIEW

**Review by MisterHW — APPROVED** [review]

**Comment by leoheck** [comment]
Hi @MisterHW I saw you approved this, nice. However, I cannot see any merge button. I think you have to do it.

**Comment by MisterHW** [comment]
I wanted to check whether there is an official recommendation whether to use tabs for indentation. The current code makes inconsistent use of tabs and spaces, which might need to be cleaned up later.

**Comment by MisterHW** [comment]
Also, thank you for your contribution :+1:

**Comment by leoheck** [comment]
Now it is super easy to understand by reading it directly on Github.

image

**Pull request merged**
